name: Playwright Tests
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
jobs:
  test:
    timeout-minutes: 20
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: |
          npm ci
          npm install -g firebase-tools
          firebase setup:emulators:database
      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Build
        run: IS_TEST_ENV=true yarn build

      - name: Start YJS server
        run: |
          cd ..
          git clone https://github.com/cpinitiative/ide-yjs.git
          cd ide-yjs
          npm install
          npm run dev &

      - name: Setup background services
        run: echo '{"rules":{".read":true,".write":true}}' > database.rules.json && FIREBASE_AUTH_EMULATOR_HOST="127.0.0.1:9099" npm start &

      - name: Run Playwright tests
        run: firebase emulators:exec "npm run test"

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30
